apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: dcrivella-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: dcrivella/auth-server:1.0.0-native
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SERVER_PORT
              value: "9000"
            - name: ISSUER_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ISSUER_URL
            - name: AUTH_TOKEN_CLIENT_AUDIENCES_CLIENT_SERVER_PKCE_0
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_TOKEN_CLIENT_AUDIENCES_CLIENT_SERVER_PKCE_0
            - name: AUTH_TOKEN_CLIENT_AUDIENCES_CLIENT_M2M_0
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_TOKEN_CLIENT_AUDIENCES_CLIENT_M2M_0
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 768Mi
