[versions]
archunit = "1.5.0"
cucumber = "7.34.6"
graalvm-buildtools-native = "1.1.9"
jacoco = "0.8.15"
mock-oauth2-server = "6.0.0"
pitest-core = "1.25.9"
pitest-gradle = "1.19.0"
pitest-junit5 = "1.2.3"
spring-boot = "4.1.0"
spring-dependency-management = "1.1.7"
spotless = "8.9.0"

[plugins]
graalvm-buildtools = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-buildtools-native" }
pitest = { id = "info.solidsoft.pitest", version.ref = "pitest-gradle" }
pitestAggregator = { id = "info.solidsoft.pitest.aggregator", version.ref = "pitest-gradle" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
cucumber-bom = { module = "io.cucumber:cucumber-bom", version.ref = "cucumber" }
cucumber-java = { module = "io.cucumber:cucumber-java" }
cucumber-junit-platform-engine = { module = "io.cucumber:cucumber-junit-platform-engine" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
lombok = { module = "org.projectlombok:lombok" }
mock-oauth2-server = { module = "no.nav.security:mock-oauth2-server", version.ref = "mock-oauth2-server" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-oauth2-authorization-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-authorization-server" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }
spring-boot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
