name: dcrivella-auth-stack

services:
  auth-server:
    image: ${AUTH_SERVER_IMAGE_NAME:-dcrivella/auth-server}:${AUTH_SERVER_IMAGE_TAG}
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: ${AUTH_SERVER_INTERNAL_PORT}
      ISSUER_URL: ${ISSUER_URL}
      AUTH_TOKEN_CLIENT_AUDIENCES_CLIENT_SERVER_PKCE_0: ${AUTH_TOKEN_CLIENT_AUDIENCES_CLIENT_SERVER_PKCE_0}
      AUTH_TOKEN_CLIENT_AUDIENCES_CLIENT_M2M_0: ${AUTH_TOKEN_CLIENT_AUDIENCES_CLIENT_M2M_0}
    networks:
      - client-side

  client-server:
    image: ${CLIENT_SERVER_IMAGE_NAME:-dcrivella/client-server}:${CLIENT_SERVER_IMAGE_TAG}
    depends_on:
      auth-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: ${CLIENT_SERVER_INTERNAL_PORT}
      ISSUER_URL: ${ISSUER_URL}
      RESOURCE_SERVER_API_URL: http://resource-server:${RESOURCE_SERVER_INTERNAL_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - client-side

  resource-server:
    image: ${RESOURCE_SERVER_IMAGE_NAME:-dcrivella/resource-server}:${RESOURCE_SERVER_IMAGE_TAG}
    depends_on:
      auth-server:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: ${RESOURCE_SERVER_INTERNAL_PORT}
      ISSUER_URL: ${ISSUER_URL}
      JWK_SET_URI: http://auth-server:${AUTH_SERVER_INTERNAL_PORT}/oauth2/jwks
      RESOURCE_AUDIENCE: ${RESOURCE_AUDIENCE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - client-side

networks:
  client-side: {}
