server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: resource-server
    version: "@projectVersion@"

  security:
    oauth2:
      resourceserver:
        jwt:
          # Must exactly equal the token's "iss" claim:
          # "iss": "http://host.docker.internal:9000"
          # If you copy a token minted before (e.g., with iss = http://localhost:9000),
          # the resource-server expecting http://host.docker.internal:9000 will reject it.
          issuer-uri: ${ISSUER_URL}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: INFO
