server:
  port: 8081

spring:
  application:
    name: resource-server
    version: "@projectVersion@"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: INFO
